#include<syslog.h>
#include"hk_log.h"

int main()
{
    syslog_init();
    HK_LOG(MY_LOG_DEBUG,"start");
    HK_LOG(MY_LOG_DEBUG,"end");
    syslog_close();
    return 0;
}

int main1(int argc,char **argv)
{
    openlog("zooyo",LOG_CONS | LOG_PID,0);
    syslog(LOG_INFO,"this is a syslog test message generated by program %s\n",argv[0]);
    closelog();
    return 0;
}
//修改 /etc/rsyslog.conf 
//service rsyslog restart 重启配置文件生效
